# Generated by Django 5.2.17 on 2026-09-04 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_number', models.CharField(max_length=12, unique=True, verbose_name='N-number')),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('fbo', 'FBO'), ('club', 'Flying club')], default='individual', max_length=12)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('owner_contact', models.CharField(blank=True, help_text='Email or phone, free text.', max_length=200)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('insurance_carrier', models.CharField(blank=True, max_length=120)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=60)),
                ('insurance_liability_per_occurrence_cents', models.PositiveBigIntegerField(default=0)),
                ('insurance_liability_per_person_cents', models.PositiveBigIntegerField(default=0)),
                ('insurance_hull_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aircraft',
                'verbose_name_plural': 'aircraft',
                'ordering': ['n_number'],
                'indexes': [models.Index(fields=['insurance_expiration'], name='aircraft_insexp_idx'), models.Index(fields=['make', 'model'], name='aircraft_make_model_idx'), models.Index(fields=['is_active'], name='aircraft_active_idx')],
            },
        ),
    ]
