# Generated by Django 6.1.1 on 2026-09-27 12:21

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import CreateExtension
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_insurance_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('pg_trgm'),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faa_code', models.CharField(max_length=16, unique=True, verbose_name='FAA code')),
                ('faa_make', models.CharField(max_length=120, verbose_name='FAA make')),
                ('faa_model', models.CharField(max_length=60, verbose_name='FAA model')),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=60)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engines', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'aircraft type',
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='AircraftTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'aircraft type alias',
                'verbose_name_plural': 'aircraft type aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_number', models.CharField(max_length=6, unique=True, verbose_name='N-number')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registrant_name', models.CharField(blank=True, max_length=160)),
                ('registrant_type', models.CharField(choices=[('individual', 'Individual'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('co_owned', 'Co-owned'), ('government', 'Government'), ('llc', 'LLC'), ('non_citizen_corporation', 'Non-citizen corporation'), ('non_citizen_co_owned', 'Non-citizen co-owned'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('pending', 'Pending'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('other', 'Other')], default='valid', max_length=16)),
                ('certificate_issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['n_number'],
            },
        ),
        migrations.CreateModel(
            name='RegistryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('types_written', models.PositiveIntegerField(default=0)),
                ('registrations_written', models.PositiveIntegerField(default=0)),
                ('types_folded', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='aircraft',
            name='aircraft_make_model_idx',
        ),
        migrations.AddIndex(
            model_name='aircrafttype',
            index=models.Index(fields=['make', 'model'], name='aircraft_type_name_idx'),
        ),
        migrations.AddIndex(
            model_name='aircrafttype',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Concat('make', models.Value(' '), 'model', output_field=models.TextField()), name='gin_trgm_ops'), name='aircraft_type_trgm_idx'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='aircraft.aircrafttype'),
        ),
        migrations.AddField(
            model_name='aircrafttypealias',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='aircraft.aircrafttype'),
        ),
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='aircraft.aircrafttype'),
        ),
        migrations.AddField(
            model_name='registryimport',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='make',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='model',
        ),
    ]
