# Generated by Django 6.1.1 on 2026-10-01 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_aircraft_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='airworthiness',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('limited', 'Limited'), ('restricted', 'Restricted'), ('experimental', 'Experimental'), ('provisional', 'Provisional'), ('multiple', 'Multiple'), ('primary', 'Primary'), ('special_flight_permit', 'Special flight permit'), ('light_sport', 'Light sport')], max_length=24),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='category',
            field=models.CharField(blank=True, choices=[('airplane', 'Airplane'), ('helicopter', 'Helicopter'), ('gyroplane', 'Gyroplane'), ('glider', 'Glider'), ('balloon', 'Balloon'), ('airship', 'Airship'), ('powered_lift', 'Powered lift'), ('weight_shift', 'Weight-shift control'), ('powered_parachute', 'Powered parachute'), ('other', 'Other')], max_length=24),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='category',
            field=models.CharField(blank=True, choices=[('airplane', 'Airplane'), ('helicopter', 'Helicopter'), ('gyroplane', 'Gyroplane'), ('glider', 'Glider'), ('balloon', 'Balloon'), ('airship', 'Airship'), ('powered_lift', 'Powered lift'), ('weight_shift', 'Weight-shift control'), ('powered_parachute', 'Powered parachute'), ('other', 'Other')], max_length=24),
        ),
        migrations.AddField(
            model_name='registration',
            name='airworthiness',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('limited', 'Limited'), ('restricted', 'Restricted'), ('experimental', 'Experimental'), ('provisional', 'Provisional'), ('multiple', 'Multiple'), ('primary', 'Primary'), ('special_flight_permit', 'Special flight permit'), ('light_sport', 'Light sport')], max_length=24),
        ),
        migrations.CreateModel(
            name='AircraftCoveragePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_categories', models.JSONField(blank=True, default=list)),
                ('excluded_airworthiness', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aircraft coverage policy',
                'verbose_name_plural': 'aircraft coverage policy',
            },
        ),
    ]
