# Generated by Django 5.2.17 on 2026-09-04 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('t60', '60 days before expiry'), ('t30', '30 days before expiry'), ('t7', '7 days before expiry'), ('expired', 'Expired today'), ('post30', '30 days after expiry')], max_length=12)),
                ('sent_at', models.DateTimeField()),
                ('to_email', models.EmailField(max_length=254)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='members.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder log entry',
                'verbose_name_plural': 'reminder log entries',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['kind', '-sent_at'], name='reminders_kind_sent_idx'), models.Index(fields=['user', '-sent_at'], name='reminders_user_sent_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'membership', 'kind'), name='reminders_once_per_kind')],
            },
        ),
    ]
