# Generated by Django 6.1.1 on 2026-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='kind',
            field=models.CharField(choices=[('first', 'First reminder'), ('second', 'Second reminder'), ('final', 'Final reminder'), ('expired', 'Expired reminder'), ('lapsed', 'Lapsed reminder')], max_length=12),
        ),
    ]
