"""Conventions about the backend's own source that no linter we run can express.

The annotation, docstring and mypy gates cover the whole backend with no ratchet left:
the adoption ratchet in ``pyproject.toml`` (``ANN``/``D`` per-file ignores and
``ignore_errors`` mypy overrides, one per unit) was deleted unit by unit as the code
was typed and documented.  A merge conflict resolved by hand can bring an entry back
without any gate noticing, since the entry only switches checks off; these tests make
that a failure.

The source is also ASCII, so a smart quote, em-dash or arrow pasted from a document
cannot reach a ``.py`` file.  A character a reader is meant to see is written as an
escape, which keeps the output and the file's bytes both correct.
"""

from __future__ import annotations

import tomllib
from pathlib import Path

PYPROJECT = Path(__file__).resolve().parents[2] / "pyproject.toml"

#: The backend tree the ASCII rule covers.
BACKEND = Path(__file__).resolve().parents[1]

#: The rule sets the ratchet used to suspend; neither may be ignored anywhere.
RATCHETED_RULES = frozenset({"ANN", "D"})


def _config() -> dict[str, object]:
    """The parsed ``pyproject.toml``."""
    with PYPROJECT.open("rb") as handle:
        return tomllib.load(handle)


def test_no_file_is_exempt_from_the_annotation_or_docstring_rules() -> None:
    """``[tool.ruff.lint.per-file-ignores]`` carries no ``ANN`` or ``D`` entry."""
    ruff_lint = _config()["tool"]["ruff"]["lint"]  # type: ignore[index]
    per_file = ruff_lint.get("per-file-ignores", {})
    exempt = {
        pattern: sorted(codes)
        for pattern, codes in per_file.items()
        if any(code.rstrip("0123456789") in RATCHETED_RULES for code in codes)
    }
    assert exempt == {}


def test_no_mypy_override_ignores_errors() -> None:
    """No ``[[tool.mypy.overrides]]`` entry carries ``ignore_errors = true``."""
    overrides = _config()["tool"]["mypy"].get("overrides", [])  # type: ignore[index]
    ignored = [entry["module"] for entry in overrides if entry.get("ignore_errors") is True]
    assert ignored == []


def _non_ascii_lines(path: Path) -> list[int]:
    """The 1-based numbers of the lines in ``path`` that hold a byte above ``0x7F``.

    The file is read as bytes rather than decoded, so a file in some other encoding
    is reported as an offending path like any other instead of raising a decoding
    error out of the check.
    """
    lines = path.read_bytes().splitlines()
    return [number for number, line in enumerate(lines, start=1) if not line.isascii()]


def test_no_backend_module_holds_a_non_ascii_character() -> None:
    """Every ``.py`` file under ``backend/`` is ASCII, migrations aside.

    Migrations are generated by Django and are not edited by hand, so they carry
    whatever a model's own strings carry.  Everywhere else, a character a reader is
    meant to see is written as a unicode escape.
    """
    offenders = {
        str(path.relative_to(BACKEND)): numbers
        for path in sorted(BACKEND.rglob("*.py"))
        if "migrations" not in path.parts
        for numbers in [_non_ascii_lines(path)]
        if numbers
    }
    assert offenders == {}
