# Generated by Django 5.2.17 on 2026-09-04 23:54

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_heading', models.CharField(blank=True, max_length=200)),
                ('hero_lede', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, default='Join CalDART', max_length=60)),
                ('primary_cta_url', models.CharField(blank=True, default='/portal/join', max_length=200)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=60)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=200)),
                ('mission_statement', wagtail.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'home page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='The California DART Network', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Volunteer disaster air transportation for California', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='info@caldart.example.org', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('mailing_address', models.TextField(blank=True)),
                ('ein', models.CharField(blank=True, max_length=20, verbose_name='EIN')),
                ('donate_url', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('theme', models.CharField(choices=[('sierra', 'Sierra (default, warm paper)'), ('pacific', 'Pacific (cool paper)'), ('night', 'Night (dark)')], default='sierra', max_length=20)),
                ('footer_text', models.TextField(blank=True, default='CalDART is a 501(c)(3) non-profit. Contributions are tax deductible.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
    ]
