# Generated by Django 5.2.17 on 2026-09-05 00:49

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_site_root'),
        ('members', '0002_initial'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19), ('two_columns', 21), ('embed', 22), ('raw_html', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section (H2)'), ('h3', 'Sub-section (H3)')], 'help_text': 'H2 headings appear in the “on this page” list.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen readers. Leave blank if decorative.', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Let the image run past the text column.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6), ('credit', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 11: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 7)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'An external URL, or a path such as /portal/join.', 'max_length': 250, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('quiet', 'Quiet')]}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small print under the button.', 'max_length': 160, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('url', 14), ('style', 15), ('note', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 7), ('description', 6)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo or other oEmbed URL.', 'icon': 'media', 'label': 'Embed', 'template': 'cms/blocks/embed.html'}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Unescaped HTML. Website administrators only.', 'icon': 'code', 'label': 'Raw HTML'})})),
            ],
            options={
                'verbose_name': 'contact page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DartIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19), ('two_columns', 21), ('embed', 22), ('raw_html', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section (H2)'), ('h3', 'Sub-section (H3)')], 'help_text': 'H2 headings appear in the “on this page” list.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen readers. Leave blank if decorative.', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Let the image run past the text column.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6), ('credit', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 11: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 7)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'An external URL, or a path such as /portal/join.', 'max_length': 250, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('quiet', 'Quiet')]}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small print under the button.', 'max_length': 160, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('url', 14), ('style', 15), ('note', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 7), ('description', 6)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo or other oEmbed URL.', 'icon': 'media', 'label': 'Embed', 'template': 'cms/blocks/embed.html'}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Unescaped HTML. Website administrators only.', 'icon': 'code', 'label': 'Raw HTML'})})),
            ],
            options={
                'verbose_name': 'DART index',
                'verbose_name_plural': 'DART indexes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'news index',
                'verbose_name_plural': 'news indexes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('members_only', models.BooleanField(default=False, help_text='Serve this page only to signed-in members with a current membership (or to DART leaders and administrators). Everyone else sees the join / renew / sign-in wall.', verbose_name='members only')),
                ('intro', models.TextField(blank=True, help_text='One or two sentences under the title.')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19), ('two_columns', 21), ('embed', 22), ('raw_html', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section (H2)'), ('h3', 'Sub-section (H3)')], 'help_text': 'H2 headings appear in the “on this page” list.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen readers. Leave blank if decorative.', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Let the image run past the text column.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6), ('credit', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 11: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 7)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'An external URL, or a path such as /portal/join.', 'max_length': 250, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('quiet', 'Quiet')]}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small print under the button.', 'max_length': 160, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('url', 14), ('style', 15), ('note', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 7), ('description', 6)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo or other oEmbed URL.', 'icon': 'media', 'label': 'Embed', 'template': 'cms/blocks/embed.html'}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Unescaped HTML. Website administrators only.', 'icon': 'code', 'label': 'Raw HTML'})})),
            ],
            options={
                'verbose_name': 'standard page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_heading',
            field=models.CharField(blank=True, default='How an activation works', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_of_operations',
            field=wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, help_text='Numbered steps describing how CalDART operates.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tax_status',
            field=wagtail.fields.RichTextField(blank=True, help_text='The 501(c)(3) note shown beside the concept of operations.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(blank=True, help_text='Shown as a pull-quote directly under the hero.'),
        ),
        migrations.CreateModel(
            name='DartPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('leader_name', models.CharField(blank=True, max_length=120)),
                ('leader_contact', models.CharField(blank=True, help_text='Email address or phone number.', max_length=200)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19), ('two_columns', 21), ('embed', 22), ('raw_html', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section (H2)'), ('h3', 'Sub-section (H3)')], 'help_text': 'H2 headings appear in the “on this page” list.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen readers. Leave blank if decorative.', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Let the image run past the text column.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6), ('credit', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 11: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 7)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'An external URL, or a path such as /portal/join.', 'max_length': 250, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('quiet', 'Quiet')]}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small print under the button.', 'max_length': 160, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('url', 14), ('style', 15), ('note', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 7), ('description', 6)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo or other oEmbed URL.', 'icon': 'media', 'label': 'Embed', 'template': 'cms/blocks/embed.html'}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Unescaped HTML. Website administrators only.', 'icon': 'code', 'label': 'Raw HTML'})})),
                ('dart', models.ForeignKey(blank=True, help_text='Links this page to the DART members can join.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='members.dart')),
            ],
            options={
                'verbose_name': 'DART page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('members_only', models.BooleanField(default=False, help_text='Serve this page only to signed-in members with a current membership (or to DART leaders and administrators). Everyone else sees the join / renew / sign-in wall.', verbose_name='members only')),
                ('date', models.DateField(verbose_name='post date')),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19), ('two_columns', 21), ('embed', 22), ('raw_html', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Section (H2)'), ('h3', 'Sub-section (H3)')], 'help_text': 'H2 headings appear in the “on this page” list.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.ParagraphBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the image for screen readers. Leave blank if decorative.', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Let the image run past the text column.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('caption', 6), ('credit', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 11: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 7)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'An external URL, or a path such as /portal/join.', 'max_length': 250, 'required': False}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('quiet', 'Quiet')]}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small print under the button.', 'max_length': 160, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('label', 12), ('page', 13), ('url', 14), ('style', 15), ('note', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 7), ('description', 6)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 3), ('image', 9), ('quote', 11), ('cta', 17), ('document', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('left', 20), ('right', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube, Vimeo or other oEmbed URL.', 'icon': 'media', 'label': 'Embed', 'template': 'cms/blocks/embed.html'}), 23: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Unescaped HTML. Website administrators only.', 'icon': 'code', 'label': 'Raw HTML'})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'news post',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
