# Generated by Django 6.1.1 on 2026-09-23 20:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_website_admin_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='concept_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='concept_of_operations',
        ),
        migrations.AddField(
            model_name='homepage',
            name='missions_flown',
            field=wagtail.fields.StreamField([('mission', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The year, or a range such as 2020-2021.', 'max_length': 9}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'What was flown, from where, to whom.', 'rows': 3}), 2: ('wagtail.blocks.StructBlock', [[('year', 0), ('text', 1)]], {})}, help_text='What CalDART has carried, newest first.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='missions_heading',
            field=models.CharField(blank=True, default='Missions flown', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='urgent_cta_label',
            field=models.CharField(blank=True, default='Request air support', help_text='The first button, shown in the alert color.', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='urgent_cta_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='The paragraphs under the mission statement.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='duty_phone',
            field=models.CharField(blank=True, help_text='Shown in the masthead as the number to call about a mission.', max_length=32, verbose_name='duty officer phone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='duty_phone_note',
            field=models.CharField(blank=True, default='Answered by the CalDART member on watch', help_text='One line under the duty officer number.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(blank=True, help_text='The mission statement, set off inside the welcome box.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tax_status',
            field=wagtail.fields.RichTextField(blank=True, help_text='The 501(c)(3) note shown in the membership box.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('duty', 'Duty (default, blue and red)'), ('sierra', 'Sierra (warm paper)'), ('pacific', 'Pacific (cool paper)'), ('night', 'Night (dark)')], default='duty', max_length=20),
        ),
    ]
