# Generated by Django 6.1.1 on 2026-09-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_block_help_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='duty_phone_note',
        ),
    ]
