# Generated by Django 6.1.1 on 2026-09-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_drop_duty_phone_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phone',
        ),
    ]
