# Generated by Django 6.1.1 on 2026-09-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('purpose', models.SlugField(max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=6)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('attachments', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email log entry',
                'verbose_name_plural': 'email log entries',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['purpose', '-sent_at'], name='mail_purpose_sent_idx'), models.Index(fields=['user', '-sent_at'], name='mail_user_sent_idx')],
            },
        ),
    ]
