# Generated by Django 6.1.1 on 2026-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='bounce_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=7),
        ),
    ]
