# Generated by Django 6.1.1 on 2026-10-03 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emaillog_bounce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('allow_opt_out', models.BooleanField(default=True)),
                ('sender_roles', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('profile', 'Email preferences'), ('unsubscribe', 'Unsubscribe link'), ('admin', 'Account administrator')], max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_opt_outs', to=settings.AUTH_USER_MODEL)),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='mail.emailtype')),
            ],
            options={
                'ordering': ['email_type__position', 'email_type__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'email_type'), name='mail_opt_out_unique')],
            },
        ),
    ]
