# Generated by Django 6.1.1 on 2026-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reactivation_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
