# Generated by Django 6.1.1 on 2026-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_reactivation_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_bounce_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
