# Generated by Django 6.1.1 on 2026-10-04 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_bounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_created',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('roles', 'Roles changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('blocked', 'Reactivation blocked'), ('unblocked', 'Reactivation allowed')], max_length=12)),
                ('added', models.JSONField(blank=True, default=list)),
                ('removed', models.JSONField(blank=True, default=list)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='account_change_idx')],
            },
        ),
    ]
