# Generated by Django 5.2.17 on 2026-09-04 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Blank means a lifetime membership.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'membership plan',
                'verbose_name_plural': 'membership plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('airport_identifier', models.CharField(blank=True, help_text='FAA identifier, e.g. E16', max_length=8)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DART',
                'verbose_name_plural': 'DARTs',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='members_dart_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('phone_alt', models.CharField(blank=True, max_length=32)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, default='CA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('home_airport_identifier', models.CharField(blank=True, max_length=8)),
                ('home_airport_city', models.CharField(blank=True, max_length=120)),
                ('air_care_alliance_number', models.CharField(blank=True, max_length=40)),
                ('pilot_certificate_type', models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('sport', 'Sport'), ('recreational', 'Recreational'), ('private', 'Private'), ('commercial', 'Commercial'), ('atp', 'Airline Transport Pilot')], default='none', max_length=16)),
                ('certificate_number', models.CharField(blank=True, max_length=40)),
                ('ifr_rated', models.CharField(choices=[('na', 'Not applicable'), ('yes', 'Yes'), ('no', 'No')], default='na', max_length=4)),
                ('ratings', models.JSONField(blank=True, default=list)),
                ('medical_type', models.CharField(choices=[('none', 'None'), ('basicmed', 'BasicMed'), ('first', 'First class'), ('second', 'Second class'), ('third', 'Third class')], default='none', max_length=16)),
                ('medical_expiration', models.DateField(blank=True, null=True)),
                ('flight_review_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('vol_ground_team', models.BooleanField(default=False, verbose_name='ground team')),
                ('vol_exercise_training', models.BooleanField(default=False, verbose_name='exercises and training')),
                ('vol_member_support', models.BooleanField(default=False, verbose_name='member support')),
                ('vol_fundraising', models.BooleanField(default=False, verbose_name='fundraising')),
                ('vol_social_media', models.BooleanField(default=False, verbose_name='social media')),
                ('vol_newsletter', models.BooleanField(default=False, verbose_name='newsletter')),
                ('notes', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, max_length=200)),
                ('aircraft', models.ManyToManyField(blank=True, related_name='pilots', to='aircraft.aircraft', verbose_name='planes commonly flown')),
                ('dart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.dart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member profile',
                'verbose_name_plural': 'member profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Blank means lifetime.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('source', models.CharField(choices=[('payment', 'Payment'), ('manual', 'Manual grant'), ('seed', 'Seed data')], default='payment', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
    ]
