# Generated by Django 6.1.1 on 2026-09-24 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('darts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Blank means a lifetime membership.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'membership plan',
                'verbose_name_plural': 'membership plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('phone_extension', models.CharField(blank=True, max_length=6)),
                ('phone_alt', models.CharField(blank=True, max_length=12)),
                ('phone_alt_extension', models.CharField(blank=True, max_length=6)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'US Virgin Islands')], default='CA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=5)),
                ('county', models.CharField(blank=True, choices=[('Alameda', 'Alameda'), ('Alpine', 'Alpine'), ('Amador', 'Amador'), ('Butte', 'Butte'), ('Calaveras', 'Calaveras'), ('Colusa', 'Colusa'), ('Contra Costa', 'Contra Costa'), ('Del Norte', 'Del Norte'), ('El Dorado', 'El Dorado'), ('Fresno', 'Fresno'), ('Glenn', 'Glenn'), ('Humboldt', 'Humboldt'), ('Imperial', 'Imperial'), ('Inyo', 'Inyo'), ('Kern', 'Kern'), ('Kings', 'Kings'), ('Lake', 'Lake'), ('Lassen', 'Lassen'), ('Los Angeles', 'Los Angeles'), ('Madera', 'Madera'), ('Marin', 'Marin'), ('Mariposa', 'Mariposa'), ('Mendocino', 'Mendocino'), ('Merced', 'Merced'), ('Modoc', 'Modoc'), ('Mono', 'Mono'), ('Monterey', 'Monterey'), ('Napa', 'Napa'), ('Nevada', 'Nevada'), ('Orange', 'Orange'), ('Placer', 'Placer'), ('Plumas', 'Plumas'), ('Riverside', 'Riverside'), ('Sacramento', 'Sacramento'), ('San Benito', 'San Benito'), ('San Bernardino', 'San Bernardino'), ('San Diego', 'San Diego'), ('San Francisco', 'San Francisco'), ('San Joaquin', 'San Joaquin'), ('San Luis Obispo', 'San Luis Obispo'), ('San Mateo', 'San Mateo'), ('Santa Barbara', 'Santa Barbara'), ('Santa Clara', 'Santa Clara'), ('Santa Cruz', 'Santa Cruz'), ('Shasta', 'Shasta'), ('Sierra', 'Sierra'), ('Siskiyou', 'Siskiyou'), ('Solano', 'Solano'), ('Sonoma', 'Sonoma'), ('Stanislaus', 'Stanislaus'), ('Sutter', 'Sutter'), ('Tehama', 'Tehama'), ('Trinity', 'Trinity'), ('Tulare', 'Tulare'), ('Tuolumne', 'Tuolumne'), ('Ventura', 'Ventura'), ('Yolo', 'Yolo'), ('Yuba', 'Yuba')], max_length=120, verbose_name='California county')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=12)),
                ('emergency_contact_phone_extension', models.CharField(blank=True, max_length=6)),
                ('home_airport_identifier', models.CharField(blank=True, max_length=3)),
                ('home_airport_city', models.CharField(blank=True, max_length=120)),
                ('air_care_alliance_number', models.CharField(blank=True, max_length=40)),
                ('pilot_certificate_type', models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('sport', 'Sport'), ('recreational', 'Recreational'), ('private', 'Private'), ('commercial', 'Commercial'), ('atp', 'Airline Transport Pilot')], default='none', max_length=16)),
                ('certificate_number', models.CharField(blank=True, max_length=40)),
                ('ifr_rated', models.CharField(choices=[('na', 'Not applicable'), ('yes', 'Yes'), ('no', 'No')], default='na', max_length=4)),
                ('ratings', models.JSONField(blank=True, default=list)),
                ('medical_type', models.CharField(choices=[('none', 'None'), ('basicmed', 'BasicMed'), ('first', 'First class'), ('second', 'Second class'), ('third', 'Third class')], default='none', max_length=16)),
                ('medical_expiration', models.DateField(blank=True, null=True)),
                ('flight_review_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('flies_rented_aircraft', models.BooleanField(default=False, verbose_name='flies rented or borrowed aircraft')),
                ('vol_mission_pilot', models.BooleanField(default=False, verbose_name='mission pilot')),
                ('vol_ground_team', models.BooleanField(default=False, verbose_name='ground team')),
                ('vol_exercise_training', models.BooleanField(default=False, verbose_name='exercises and training')),
                ('vol_member_support', models.BooleanField(default=False, verbose_name='member support')),
                ('vol_fundraising', models.BooleanField(default=False, verbose_name='fundraising')),
                ('vol_social_media', models.BooleanField(default=False, verbose_name='social media')),
                ('vol_newsletter', models.BooleanField(default=False, verbose_name='newsletter')),
                ('member_since', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('how_heard', models.CharField(blank=True, max_length=200)),
                ('aircraft', models.ManyToManyField(blank=True, related_name='pilots', to='aircraft.aircraft', verbose_name='planes commonly flown')),
                ('dart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='darts.dart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member profile',
                'verbose_name_plural': 'member profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Blank means lifetime.', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=12)),
                ('source', models.CharField(choices=[('payment', 'Payment'), ('manual', 'Manual grant'), ('seed', 'Seed data')], default='payment', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
    ]
