# Generated by Django 6.1.1 on 2026-09-24 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='members.membershipplan'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['medical_expiration'], name='members_prof_medexp_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['pilot_certificate_type'], name='members_prof_cert_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', '-ends_on'], name='members_mship_user_end_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['status', 'ends_on'], name='members_mship_status_idx'),
        ),
    ]
