# Generated by Django 6.1.1 on 2026-09-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=12),
        ),
    ]
