# Generated by Django 6.1.1 on 2026-09-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_membership_new_status"),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='flies_rented_aircraft',
            field=models.BooleanField(default=False, verbose_name='flies rented or borrowed aircraft'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='vol_mission_pilot',
            field=models.BooleanField(default=False, verbose_name='mission pilot'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='county',
            field=models.CharField(blank=True, choices=[('Alameda', 'Alameda'), ('Alpine', 'Alpine'), ('Amador', 'Amador'), ('Butte', 'Butte'), ('Calaveras', 'Calaveras'), ('Colusa', 'Colusa'), ('Contra Costa', 'Contra Costa'), ('Del Norte', 'Del Norte'), ('El Dorado', 'El Dorado'), ('Fresno', 'Fresno'), ('Glenn', 'Glenn'), ('Humboldt', 'Humboldt'), ('Imperial', 'Imperial'), ('Inyo', 'Inyo'), ('Kern', 'Kern'), ('Kings', 'Kings'), ('Lake', 'Lake'), ('Lassen', 'Lassen'), ('Los Angeles', 'Los Angeles'), ('Madera', 'Madera'), ('Marin', 'Marin'), ('Mariposa', 'Mariposa'), ('Mendocino', 'Mendocino'), ('Merced', 'Merced'), ('Modoc', 'Modoc'), ('Mono', 'Mono'), ('Monterey', 'Monterey'), ('Napa', 'Napa'), ('Nevada', 'Nevada'), ('Orange', 'Orange'), ('Placer', 'Placer'), ('Plumas', 'Plumas'), ('Riverside', 'Riverside'), ('Sacramento', 'Sacramento'), ('San Benito', 'San Benito'), ('San Bernardino', 'San Bernardino'), ('San Diego', 'San Diego'), ('San Francisco', 'San Francisco'), ('San Joaquin', 'San Joaquin'), ('San Luis Obispo', 'San Luis Obispo'), ('San Mateo', 'San Mateo'), ('Santa Barbara', 'Santa Barbara'), ('Santa Clara', 'Santa Clara'), ('Santa Cruz', 'Santa Cruz'), ('Shasta', 'Shasta'), ('Sierra', 'Sierra'), ('Siskiyou', 'Siskiyou'), ('Solano', 'Solano'), ('Sonoma', 'Sonoma'), ('Stanislaus', 'Stanislaus'), ('Sutter', 'Sutter'), ('Tehama', 'Tehama'), ('Trinity', 'Trinity'), ('Tulare', 'Tulare'), ('Tuolumne', 'Tuolumne'), ('Ventura', 'Ventura'), ('Yolo', 'Yolo'), ('Yuba', 'Yuba')], max_length=120, verbose_name='California county'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'US Virgin Islands')], default='CA', max_length=2),
        ),
    ]
