# Generated by Django 6.1.1 on 2026-10-01 04:24

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='ham_callsign',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(re.compile('^(?:[KNW][A-Z]?|A[A-L])[0-9][A-Z]{1,3}$'), 'Enter a US amateur radio callsign, such as W6ABC.')], verbose_name='amateur radio callsign'),
        ),
    ]
