# Generated by Django 6.1.1 on 2026-10-05 23:10

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_ham_callsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]{7}$'), 'Enter the 7 digits of the pilot certificate number.')]),
        ),
    ]
