# Generated by Django 6.1.1 on 2026-10-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Waiting to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('stopped', 'Stopped')], default='draft', max_length=7)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('confirm_count', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_emails_sent', to=settings.AUTH_USER_MODEL)),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_emails_stopped', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BatchAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('already_count', models.PositiveIntegerField(default=0)),
                ('bulk_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='bulk_email.bulkemail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BulkEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=301)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('kind', models.CharField(blank=True, choices=[('member', 'Member'), ('friend', 'Friend')], max_length=6)),
                ('dart_name', models.CharField(blank=True, max_length=60)),
                ('round', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('batched', 'In the batch'), ('pending', 'Not sent yet'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('stopped', 'Not sent (stopped)'), ('bounced', 'Bounced')], default='batched', max_length=7)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('tried_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='bulk_email.batchadd')),
                ('bulk_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='bulk_email.bulkemail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_emails_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkemail',
            index=models.Index(fields=['status', 'start_at'], name='bulk_email__status_f1a98f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkemailrecipient',
            index=models.Index(fields=['bulk_email', 'status'], name='bulk_email__bulk_em_77f831_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkemailrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('bulk_email', 'user', 'round'), name='bulk_email_recipient_once_per_round'),
        ),
    ]
