# Generated by Django 6.1.1 on 2026-10-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0002_images_and_values'),
        ('mail', '0004_default_email_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='email_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_emails', to='mail.emailtype'),
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='not_sent_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
