# Generated by Django 6.1.1 on 2026-10-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0003_bulkemail_email_type'),
        ('darts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='dart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_emails', to='darts.dart'),
        ),
    ]
