# Generated by Django 6.1.1 on 2026-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0004_bulkemail_dart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
