# Generated by Django 6.1.1 on 2026-10-03 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0005_bulkemail_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='bounced_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='hidden_from_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkemailrecipient',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BulkEmailRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField()),
                ('bulk_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='bulk_email.bulkemail')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_email_retries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_at', 'id'],
            },
        ),
    ]
