# Generated by Django 6.1.1 on 2026-10-03 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0007_templates_and_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='is_callout',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Callout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closes_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('bulk_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callout', to='bulk_email.bulkemail')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callouts_closed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalloutAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('available', 'Available'), ('limited', 'Available with limits'), ('unavailable', 'Not available')], max_length=11)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('answered_at', models.DateTimeField()),
                ('callout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bulk_email.callout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callout_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['answered_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('callout', 'user'), name='callout_answer_once')],
            },
        ),
    ]
