# Generated by Django 6.1.1 on 2026-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0008_callouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkemailrecipient',
            name='status',
            field=models.CharField(choices=[('batched', 'On the list'), ('pending', 'Not sent yet'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('stopped', 'Not sent (stopped)'), ('bounced', 'Bounced')], default='batched', max_length=7),
        ),
    ]
