# Generated by Django 5.2.17 on 2026-09-04 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total charged.')),
                ('plan_amount_cents', models.PositiveIntegerField(default=0)),
                ('contribution_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mock', 'Mock')], max_length=12)),
                ('wallet', models.CharField(choices=[('card', 'Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('link', 'Link'), ('paypal', 'PayPal'), ('mock', 'Mock'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('provider_ref', models.CharField(blank=True, help_text='PaymentIntent id / PayPal order id.', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(blank=True, help_text='Null for a pure donation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_user_created_idx'), models.Index(fields=['status', '-completed_at'], name='payments_status_idx'), models.Index(fields=['provider', 'status'], name='payments_provider_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='payments_provider_ref_unique')],
            },
        ),
    ]
