# Generated by Django 6.1.1 on 2026-09-24 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total charged.')),
                ('plan_amount_cents', models.PositiveIntegerField(default=0)),
                ('contribution_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mock', 'Mock'), ('manual', 'Recorded by hand')], max_length=12)),
                ('wallet', models.CharField(choices=[('card', 'Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('link', 'Link'), ('paypal', 'PayPal'), ('mock', 'Mock'), ('check', 'Check'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('provider_ref', models.CharField(blank=True, help_text='PaymentIntent id / PayPal order id.', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fee_cents', models.PositiveIntegerField(default=0, help_text="The provider's fee, as the provider reported it.")),
                ('net_cents', models.PositiveIntegerField(default=0, help_text="What reached CalDART's balance, as the provider reported it.")),
                ('receipt_sent_at', models.DateTimeField(blank=True, help_text="When CalDART's own receipt was last emailed.", null=True)),
                ('received_on', models.DateField(blank=True, help_text='For a payment recorded by hand, the day the money was received.', null=True)),
                ('reconciled_on', models.DateField(blank=True, help_text='The day a treasurer matched this to a statement.', null=True)),
                ('note', models.CharField(blank=True, help_text="A treasurer's note: the check number, the reason for a manual entry.", max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(blank=True, help_text='Null for a pure donation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.membershipplan')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reconciled', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The administrator who recorded a payment taken by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Protected: a payment is a financial record and outlives the account.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_user_created_idx'), models.Index(fields=['status', '-completed_at'], name='payments_status_idx'), models.Index(fields=['provider', 'status'], name='payments_provider_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='payments_provider_ref_unique')],
            },
        ),
        migrations.CreateModel(
            name='RenewalMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_cents', models.PositiveIntegerField(default=0, help_text='Renewed alongside the dues.')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mock', 'Mock')], max_length=12)),
                ('customer_ref', models.CharField(blank=True, help_text='Stripe customer id / PayPal payer id.', max_length=128)),
                ('method_ref', models.CharField(help_text='Stripe payment method id / PayPal vault id.', max_length=128)),
                ('method_brand', models.CharField(blank=True, max_length=32)),
                ('method_last4', models.CharField(blank=True, max_length=4)),
                ('method_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('method_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('method_label', models.CharField(help_text='What the member sees: "Visa ending 4242, expires 03/2028".', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed charges; reset on success.')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('last_charged_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('canceled_by', models.ForeignKey(blank=True, help_text='The member themselves, or the administrator who turned it off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_mandates_canceled', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Null when the member is a life member and only the contribution renews.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_mandates', to='members.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_mandate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenewalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_on', models.DateField(help_text='The day the charge is due.')),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=12)),
                ('error', models.CharField(blank=True, help_text="The provider's decline reason, for the member.", max_length=255)),
                ('noticed_at', models.DateTimeField(blank=True, help_text='When the advance-warning email went out.', null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('result_emailed_at', models.DateTimeField(blank=True, help_text='When the charged or failed email went out.', null=True)),
                ('membership', models.ForeignKey(help_text='The term whose expiry this charge renews.', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_attempts', to='members.membership')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_attempts', to='payments.payment')),
                ('retry_of', models.ForeignKey(blank=True, help_text='The attempt this one retries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payments.renewalattempt')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.renewalmandate')),
            ],
            options={
                'ordering': ['-scheduled_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='What was given back.')),
                ('reason', models.CharField(choices=[('requested_by_member', 'Requested by the member'), ('duplicate', 'Duplicate payment'), ('error', 'Charged in error'), ('fraudulent', 'Fraudulent'), ('other', 'Other')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('provider_ref', models.CharField(blank=True, help_text='The Stripe or PayPal refund id; blank for a manual or mock refund.', max_length=128)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(help_text='Protected: a refund is a financial record, and the payment it reverses cannot be deleted out from under it.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, help_text="Null when the refund was issued in the provider's own dashboard.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='payments_refund_pay_idx'), models.Index(fields=['status', '-refunded_at'], name='payments_refund_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='renewalmandate',
            index=models.Index(fields=['status', '-created_at'], name='payments_mandate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalattempt',
            index=models.Index(fields=['mandate', '-scheduled_on'], name='payments_attempt_man_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalattempt',
            index=models.Index(fields=['outcome', 'scheduled_on'], name='payments_attempt_out_idx'),
        ),
    ]
