# Generated by Django 6.1.1 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Paid'), ('failed', 'Failed'), ('partially_refunded', 'Partly refunded'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='renewalattempt',
            name='outcome',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('succeeded', 'Charged'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=12),
        ),
    ]
