# Generated by Django 6.1.1 on 2026-09-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('airport_identifiers', models.CharField(help_text='FAA or ICAO identifiers, separated by commas, e.g. CCR, C83', max_length=120)),
                ('website_url', models.URLField(blank=True, help_text="The team's own site, if it has one.", verbose_name='website')),
                ('is_active', models.BooleanField(default=True)),
                ('roster_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DART',
                'verbose_name_plural': 'DARTs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='darts_dart_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='DartContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(help_text='The job, e.g. DART leader.', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('receives_roster', models.BooleanField(default=False)),
                ('dart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='darts.dart')),
            ],
            options={
                'verbose_name': 'DART contact',
                'verbose_name_plural': 'DART contacts',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
